/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConditionRouteImport } from './routes/condition'
import { Route as InvestmentRouteImport } from './routes/investment'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RoadsRouteImport } from './routes/roads'
import { Route as SummaryRouteImport } from './routes/summary'
import { Route as WardsRouteImport } from './routes/wards'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionRoute = ConditionRouteImport.update({
  id: '/condition',
  path: '/condition',
  getParentRoute: () => rootRouteImport,
} as any)
const InvestmentRoute = InvestmentRouteImport.update({
  id: '/investment',
  path: '/investment',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadsRoute = RoadsRouteImport.update({
  id: '/roads',
  path: '/roads',
  getParentRoute: () => rootRouteImport,
} as any)
const SummaryRoute = SummaryRouteImport.update({
  id: '/summary',
  path: '/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const WardsRoute = WardsRouteImport.update({
  id: '/wards',
  path: '/wards',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/condition': typeof ConditionRoute
  '/investment': typeof InvestmentRoute
  '/login': typeof LoginRoute
  '/roads': typeof RoadsRoute
  '/summary': typeof SummaryRoute
  '/wards': typeof WardsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/condition': typeof ConditionRoute
  '/investment': typeof InvestmentRoute
  '/login': typeof LoginRoute
  '/roads': typeof RoadsRoute
  '/summary': typeof SummaryRoute
  '/wards': typeof WardsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/condition': typeof ConditionRoute
  '/investment': typeof InvestmentRoute
  '/login': typeof LoginRoute
  '/roads': typeof RoadsRoute
  '/summary': typeof SummaryRoute
  '/wards': typeof WardsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/condition'
    | '/investment'
    | '/login'
    | '/roads'
    | '/summary'
    | '/wards'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/condition'
    | '/investment'
    | '/login'
    | '/roads'
    | '/summary'
    | '/wards'
  id:
    | '__root__'
    | '/'
    | '/condition'
    | '/investment'
    | '/login'
    | '/roads'
    | '/summary'
    | '/wards'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConditionRoute: typeof ConditionRoute
  InvestmentRoute: typeof InvestmentRoute
  LoginRoute: typeof LoginRoute
  RoadsRoute: typeof RoadsRoute
  SummaryRoute: typeof SummaryRoute
  WardsRoute: typeof WardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condition': {
      id: '/condition'
      path: '/condition'
      fullPath: '/condition'
      preLoaderRoute: typeof ConditionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/investment': {
      id: '/investment'
      path: '/investment'
      fullPath: '/investment'
      preLoaderRoute: typeof InvestmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roads': {
      id: '/roads'
      path: '/roads'
      fullPath: '/roads'
      preLoaderRoute: typeof RoadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/summary': {
      id: '/summary'
      path: '/summary'
      fullPath: '/summary'
      preLoaderRoute: typeof SummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wards': {
      id: '/wards'
      path: '/wards'
      fullPath: '/wards'
      preLoaderRoute: typeof WardsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConditionRoute: ConditionRoute,
  InvestmentRoute: InvestmentRoute,
  LoginRoute: LoginRoute,
  RoadsRoute: RoadsRoute,
  SummaryRoute: SummaryRoute,
  WardsRoute: WardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
